services:

    Intonation\GridBundle\Service\GridService:
        autowire: true

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    Prezent\Grid\DefaultGridFactory: '@grid_factory'

    Intonation\GridBundle\Twig\GridExtension:
        tags:
            - { name: twig.extension }
